### ISSUE TITLE
如何启动

### ISSUE THREAD

**Issue by simon-p-j-r** [boy56/PLMEE#17]
博主，你好！
我在尝试启动代码进行训练的时候，首先在src文件夹下创建了BertPara文件夹存放bert模型文件，随后在PLMEE文件夹下创建了data数据，将从赛事上下载的数据放入，并运行了data_convert.py文件。但是在实际运行项目时却会报错：
  File "/home/nlp/pjr/seminar/eight/PLMEE/src/extractor_trainer.py", line 6, in <module>
    from allennlp.modules.token_embedders.bert_token_embedder import PretrainedBertEmbedder
  File "/home/nlp/anaconda3/envs/pjr/lib/python3.7/site-packages/allennlp/modules/__init__.py", line 9, in <module>
    from allennlp.modules.elmo import Elmo
  File "/home/nlp/anaconda3/envs/pjr/lib/python3.7/site-packages/allennlp/modules/elmo.py", line 20, in <module>
    from allennlp.modules.highway import Highway
  File "/home/nlp/anaconda3/envs/pjr/lib/python3.7/site-packages/allennlp/modules/highway.py", line 12, in <module>
    class Highway(torch.nn.Module):
  File "/home/nlp/anaconda3/envs/pjr/lib/python3.7/site-packages/allennlp/modules/highway.py", line 49, in Highway
    def forward(self, inputs: torch.Tensor) -> torch.Tensor:  # pylint: disable=arguments-differ
  File "/home/nlp/anaconda3/envs/pjr/lib/python3.7/site-packages/overrides/overrides.py", line 83, in overrides
    return _overrides(method, check_signature, check_at_runtime)
  File "/home/nlp/anaconda3/envs/pjr/lib/python3.7/site-packages/overrides/overrides.py", line 170, in _overrides
    _validate_method(method, super_class, check_signature)
  File "/home/nlp/anaconda3/envs/pjr/lib/python3.7/site-packages/overrides/overrides.py", line 189, in _validate_method
    ensure_signature_is_compatible(super_method, method, is_static)
  File "/home/nlp/anaconda3/envs/pjr/lib/python3.7/site-packages/overrides/signature.py", line 113, in ensure_signature_is_compatible
    method_name,
  File "/home/nlp/anaconda3/envs/pjr/lib/python3.7/site-packages/overrides/signature.py", line 220, in ensure_all_positional_args_defined_in_sub
    raise TypeError(f"{method_name}: `{super_param.name}` must be present")
TypeError: Highway.forward: `input` must be present

进程已结束，退出代码为 1
请问是为什么呢？

**Comment by 1611064578** [comment]
你好 我也在跑这个模型 ，您下载的环境是 allennlp0.9.0  typorch 1.4.0吗 ，我这里显示好多包导不进来，
比如extractor_trainer.py中 16 17行的
from allennlp.modules.token_embedders.bert_token_embedder import PretrainedBertEmbedder
from allennlp.data.token_indexers.wordpiece_indexer import PretrainedBertIndexer
您有这样的问题吗，可以帮忙解答一下吗，谢谢了

**Comment by simon-p-j-r** [comment]
新疆一个虚拟环境，重新导入包，allennlp在导入的时候确实容易冲突
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "boy56/PLMEE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月21日(星期二) 上午10:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [boy56/PLMEE] 如何启动 (Issue #17)





 
你好 我也在跑这个模型 ，您下载的环境是 allennlp0.9.0  typorch 1.4.0吗 ，我这里显示好多包导不进来，
 比如extractor_trainer.py中 16 17行的
 from allennlp.modules.token_embedders.bert_token_embedder import PretrainedBertEmbedder
 from allennlp.data.token_indexers.wordpiece_indexer import PretrainedBertIndexer
 您有这样的问题吗，可以帮忙解答一下吗，谢谢了

**Comment by 1611064578** [comment]
谢谢您 我试一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "boy56/PLMEE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月21日(星期二) 上午10:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [boy56/PLMEE] 如何启动 (Issue #17)





 新疆一个虚拟环境，重新导入包，allennlp在导入的时候确实容易冲突 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "boy56/PLMEE"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2023年2月21日(星期二) 上午10:46 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [boy56/PLMEE] 如何启动 (Issue #17) 
 
 
 
 
 
   
 你好 我也在跑这个模型 ，您下载的环境是 allennlp0.9.0  typorch 1.4.0吗 ，我这里显示好多包导不进来， 
  比如extractor_trainer.py中 16 17行的 
  from allennlp.modules.token_embedders.bert_token_embedder import PretrainedBertEmbedder 
  from allennlp.data.token_indexers.wordpiece_indexer import PretrainedBertIndexer 
  您有这样的问题吗，可以帮忙解答一下吗，谢谢了

**Comment by boy56** [comment]
> 博主，你好！ 我在尝试启动代码进行训练的时候，首先在src文件夹下创建了BertPara文件夹存放bert模型文件，随后在PLMEE文件夹下创建了data数据，将从赛事上下载的数据放入，并运行了data_convert.py文件。但是在实际运行项目时却会报错： File "/home/nlp/pjr/seminar/eight/PLMEE/src/extractor_trainer.py", line 6, in from allennlp.modules.token_embedders.bert_token_embedder import PretrainedBertEmbedder File "/home/nlp/anaconda3/envs/pjr/lib/python3.7/site-packages/allennlp/modules/**init**.py", line 9, in from allennlp.modules.elmo import Elmo File "/home/nlp/anaconda3/envs/pjr/lib/python3.7/site-packages/allennlp/modules/elmo.py", line 20, in from allennlp.modules.highway import Highway File "/home/nlp/anaconda3/envs/pjr/lib/python3.7/site-packages/allennlp/modules/highway.py", line 12, in class Highway(torch.nn.Module): File "/home/nlp/anaconda3/envs/pjr/lib/python3.7/site-packages/allennlp/modules/highway.py", line 49, in Highway def forward(self, inputs: torch.Tensor) -> torch.Tensor: # pylint: disable=arguments-differ File "/home/nlp/anaconda3/envs/pjr/lib/python3.7/site-packages/overrides/overrides.py", line 83, in overrides return _overrides(method, check_signature, check_at_runtime) File "/home/nlp/anaconda3/envs/pjr/lib/python3.7/site-packages/overrides/overrides.py", line 170, in _overrides _validate_method(method, super_class, check_signature) File "/home/nlp/anaconda3/envs/pjr/lib/python3.7/site-packages/overrides/overrides.py", line 189, in _validate_method ensure_signature_is_compatible(super_method, method, is_static) File "/home/nlp/anaconda3/envs/pjr/lib/python3.7/site-packages/overrides/signature.py", line 113, in ensure_signature_is_compatible method_name, File "/home/nlp/anaconda3/envs/pjr/lib/python3.7/site-packages/overrides/signature.py", line 220, in ensure_all_positional_args_defined_in_sub raise TypeError(f"{method_name}: `{super_param.name}` must be present") TypeError: Highway.forward: `input` must be present
> 
> 进程已结束，退出代码为 1 请问是为什么呢？

这个错误我确实没遇到过，我建议你去搜一下allennlp相关的一些报错信息，有没有一些类似的经验贴。就目前报错信息我猜可能是tokenizer这步骤导致的，主要是看看BERT的版本是否和他这个框架适配。我也很久没用过这个框架了......

**Comment by 1611064578** [comment]
您好，我试了一下。跑起来了，还挺快的，但是显示`scheduler.step()` 。

scheduler.step（）&nbsp;中的 epoch 参数不是必需的，在可能的情况下被弃用。请使用&nbsp;scheduler.step（）&nbsp;来步进调度程序。



我跑了两遍都是这个问题，这个我确实不太理解，你能说一下吗？谢谢您
------------------ 原始邮件 ------------------
发件人:                                                                                                                        "boy56/PLMEE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月21日(星期二) 上午10:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [boy56/PLMEE] 如何启动 (Issue #17)





 新疆一个虚拟环境，重新导入包，allennlp在导入的时候确实容易冲突 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "boy56/PLMEE"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2023年2月21日(星期二) 上午10:46 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [boy56/PLMEE] 如何启动 (Issue #17) 
 
 
 
 
 
   
 你好 我也在跑这个模型 ，您下载的环境是 allennlp0.9.0  typorch 1.4.0吗 ，我这里显示好多包导不进来， 
  比如extractor_trainer.py中 16 17行的 
  from allennlp.modules.token_embedders.bert_token_embedder import PretrainedBertEmbedder 
  from allennlp.data.token_indexers.wordpiece_indexer import PretrainedBertIndexer 
  您有这样的问题吗，可以帮忙解答一下吗，谢谢了

**Comment by simon-p-j-r** [comment]
哥们，我自己都没跑起来呢，你还是跑起来了的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "boy56/PLMEE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月22日(星期三) 中午11:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [boy56/PLMEE] 如何启动 (Issue #17)





 您好，我试了一下。跑起来了，还挺快的，但是显示`scheduler.step()` 。 
 
 scheduler.step（）&amp;nbsp;中的 epoch 参数不是必需的，在可能的情况下被弃用。请使用&amp;nbsp;scheduler.step（）&amp;nbsp;来步进调度程序。 
 
 
 
 我跑了两遍都是这个问题，这个我确实不太理解，你能说一下吗？谢谢您 
 ------------------ 原始邮件 ------------------ 
 发件人:                                                                                                                        "boy56/PLMEE"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2023年2月21日(星期二) 上午10:48 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [boy56/PLMEE] 如何启动 (Issue #17) 
 
 
 
 
 
  新疆一个虚拟环境，重新导入包，allennlp在导入的时候确实容易冲突  
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "boy56/PLMEE"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2023年2月21日(星期二) 上午10:46  
  ***@***.***&amp;amp;gt;;  
  ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [boy56/PLMEE] 如何启动 (Issue #17)  
   
   
   
   
   
     
  你好 我也在跑这个模型 ，您下载的环境是 allennlp0.9.0  typorch 1.4.0吗 ，我这里显示好多包导不进来，  
   比如extractor_trainer.py中 16 17行的  
   from allennlp.modules.token_embedders.bert_token_embedder import PretrainedBertEmbedder  
   from allennlp.data.token_indexers.wordpiece_indexer import PretrainedBertIndexer  
   您有这样的问题吗，可以帮忙解答一下吗，谢谢了

**Comment by 1611064578** [comment]
> 哥们，我自己都没跑起来呢，你还是跑起来了的
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "boy56/PLMEE" ***@***.***&gt;; 发送时间:&nbsp;2023年2月22日(星期三) 中午11:57 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [boy56/PLMEE] 如何启动 (Issue #17) 您好，我试了一下。跑起来了，还挺快的，但是显示`scheduler.step()` 。 scheduler.step（）&amp;nbsp;中的 epoch 参数不是必需的，在可能的情况下被弃用。请使用&amp;nbsp;scheduler.step（）&amp;nbsp;来步进调度程序。 我跑了两遍都是这个问题，这个我确实不太理解，你能说一下吗？谢谢您 ------------------ 原始邮件 ------------------ 发件人: "boy56/PLMEE" ***@***.***&amp;gt;; 发送时间:&amp;nbsp;2023年2月21日(星期二) 上午10:48 ***@***.***&amp;gt;; ***@***.******@***.***&amp;gt;; 主题:&amp;nbsp;Re: [boy56/PLMEE] 如何启动 (Issue #17) 新疆一个虚拟环境，重新导入包，allennlp在导入的时候确实容易冲突 ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------ 发件人: "boy56/PLMEE" ***@***.***&amp;amp;gt;; 发送时间:&amp;amp;nbsp;2023年2月21日(星期二) 上午10:46 ***@***.***&amp;amp;gt;; ***@***.******@***.***&amp;amp;gt;; 主题:&amp;amp;nbsp;Re: [boy56/PLMEE] 如何启动 (Issue #17) 你好 我也在跑这个模型 ，您下载的环境是 allennlp0.9.0 typorch 1.4.0吗 ，我这里显示好多包导不进来， 比如extractor_trainer.py中 16 17行的 from allennlp.modules.token_embedders.bert_token_embedder import PretrainedBertEmbedder from allennlp.data.token_indexers.wordpiece_indexer import PretrainedBertIndexer 您有这样的问题吗，可以帮忙解答一下吗，谢谢了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&amp;amp;gt; — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&amp;gt; — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

我之前也遇到过这个问题

**Comment by simon-p-j-r** [comment]
哥们，你可以跟我讲一下你跑这个模型具体的操作步骤吗？我试了几次始终有错。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "boy56/PLMEE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月22日(星期三) 中午11:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [boy56/PLMEE] 如何启动 (Issue #17)





 您好，我试了一下。跑起来了，还挺快的，但是显示`scheduler.step()` 。 
 
 scheduler.step（）&amp;nbsp;中的 epoch 参数不是必需的，在可能的情况下被弃用。请使用&amp;nbsp;scheduler.step（）&amp;nbsp;来步进调度程序。 
 
 
 
 我跑了两遍都是这个问题，这个我确实不太理解，你能说一下吗？谢谢您 
 ------------------ 原始邮件 ------------------ 
 发件人:                                                                                                                        "boy56/PLMEE"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2023年2月21日(星期二) 上午10:48 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [boy56/PLMEE] 如何启动 (Issue #17) 
 
 
 
 
 
  新疆一个虚拟环境，重新导入包，allennlp在导入的时候确实容易冲突  
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "boy56/PLMEE"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2023年2月21日(星期二) 上午10:46  
  ***@***.***&amp;amp;gt;;  
  ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [boy56/PLMEE] 如何启动 (Issue #17)  
   
   
   
   
   
     
  你好 我也在跑这个模型 ，您下载的环境是 allennlp0.9.0  typorch 1.4.0吗 ，我这里显示好多包导不进来，  
   比如extractor_trainer.py中 16 17行的  
   from allennlp.modules.token_embedders.bert_token_embedder import PretrainedBertEmbedder  
   from allennlp.data.token_indexers.wordpiece_indexer import PretrainedBertIndexer  
   您有这样的问题吗，可以帮忙解答一下吗，谢谢了
